# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0021_sso_id_verification'),
        ('third_party_auth', '0013_merge'),
    ]

    operations = [
    ]
